[package]
name = "scx_stats_derive"
version = "1.0.6"
edition = "2021"
authors = ["Tejun Heo <tj@kernel.org>"]
license = "GPL-2.0-only"
repository = "https://github.com/sched-ext/scx"
description = "Derive macro for scx_stats"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
scx_stats = { workspace = true }
serde_json = { workspace = true }
syn = { workspace = true }
