[package]
name = "scx_bpfland"
version = "1.0.6"
authors = ["Andrea Righi <andrea.righi@linux.dev>"]
edition = "2021"
description = "A vruntime-based sched_ext scheduler that prioritizes interactive workloads. https://github.com/sched-ext/scx/tree/main"
license = "GPL-2.0-only"

[dependencies]
anyhow = { workspace = true }
ctrlc = { workspace = true }
clap = { workspace = true }
crossbeam = { workspace = true }
libbpf-rs = { workspace = true }
log = { workspace = true }
scx_stats = { workspace = true }
scx_stats_derive = { workspace = true }
scx_utils = { workspace = true }
serde = { workspace = true }
simplelog = { workspace = true }

[build-dependencies]
scx_utils = { workspace = true }

[features]
enable_backtrace = []
