[package]
name = "scx_utils"
version = "1.0.7"
edition = "2021"
authors = ["Tejun Heo <tj@kernel.org>"]
license = "GPL-2.0-only"
repository = "https://github.com/sched-ext/scx"
description = "Utilities for sched_ext schedulers"

[dependencies]
anyhow = { workspace = true }
bindgen = { workspace = true }
bitvec = { workspace = true }
glob = { workspace = true }
hex = { workspace = true }
lazy_static = { workspace = true }
libbpf-cargo = { workspace = true }
libbpf-rs = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
metrics = { workspace = true }
metrics-util = { workspace = true }
nvml-wrapper = { workspace = true, optional = true }
paste = { workspace = true }
regex = { workspace = true }
scx_stats = { workspace = true }
serde = { workspace = true }
sscanf = { workspace = true }
tar = { workspace = true }
version-compare = { workspace = true }
walkdir = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
bindgen = { workspace = true }
glob = { workspace = true }
lazy_static = { workspace = true }
sscanf = { workspace = true }
tar = { workspace = true }
vergen = { workspace = true }
version-compare = { workspace = true }
walkdir = { workspace = true }

[features]
default = []
gpu-topology = ["dep:nvml-wrapper"]
