[package]
name = "scx_layered"
version = "1.0.7"
authors = ["Tejun Heo <htejun@meta.com>", "Meta"]
edition = "2021"
description = "A highly configurable multi-layer BPF / user space hybrid scheduler used within sched_ext, which is a Linux kernel feature which enables implementing kernel thread schedulers in BPF and dynamically loading them. https://github.com/sched-ext/scx/tree/main"
license = "GPL-2.0-only"

[dependencies]
anyhow = { workspace = true }
bitvec = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
crossbeam = { workspace = true }
ctrlc = { workspace = true }
fastrand = { workspace = true }
fb_procfs = { workspace = true }
lazy_static = { workspace = true }
libbpf-rs = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
scx_stats = { workspace = true }
scx_stats_derive = { workspace = true }
scx_utils = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
simplelog = { workspace = true }

[build-dependencies]
scx_utils = { workspace = true }

[features]
enable_backtrace = []
