[package]
name = "scx_rusty"
version = "1.0.6"
authors = ["Dan Schatzberg <dschatzberg@meta.com>", "Meta"]
edition = "2021"
description = "A multi-domain, BPF / user space hybrid scheduler used within sched_ext, which is a Linux kernel feature which enables implementing kernel thread schedulers in BPF and dynamically loading them. https://github.com/sched-ext/scx/tree/main"
license = "GPL-2.0-only"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
crossbeam = { workspace = true }
ctrlc = { workspace = true }
fb_procfs = { workspace = true }
libbpf-rs = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
ordered-float = { workspace = true }
scx_stats = { workspace = true }
scx_stats_derive = { workspace = true }
scx_utils = { workspace = true }
serde = { workspace = true }
simplelog = { workspace = true }
sorted-vec = { workspace = true }
static_assertions = { workspace = true }

[build-dependencies]
scx_utils = { workspace = true }

[features]
enable_backtrace = []
