[package]
name = "scx_rustland"
version = "1.0.6"
authors = ["Andrea Righi <andrea.righi@linux.dev>"]
edition = "2021"
description = "A BPF component (dispatcher) that implements the low level sched-ext functionalities and a user-space counterpart (scheduler), written in Rust, that implements the actual scheduling policy. This is used within sched_ext, which is a Linux kernel feature which enables implementing kernel thread schedulers in BPF and dynamically loading them. https://github.com/sched-ext/scx/tree/main"
license = "GPL-2.0-only"

[dependencies]
anyhow = { workspace = true }
plain = { workspace = true }
clap = { workspace = true }
ctrlc = { workspace = true }
libbpf-rs = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
scx_stats = { workspace = true }
scx_stats_derive = { workspace = true }
scx_utils = { workspace = true }
scx_rustland_core = { workspace = true }
simplelog = { workspace = true }

[build-dependencies]
scx_utils = { workspace = true }
scx_rustland_core = { workspace = true }

[features]
enable_backtrace = []
