[package]
name = "scx_lavd"
version = "1.0.6"
authors = ["Changwoo Min <changwoo@igalia.com>", "Igalia"]
edition = "2021"
description = "A Latency-criticality Aware Virtual Deadline (LAVD) scheduler based on sched_ext, which is a Linux kernel feature which enables implementing kernel thread schedulers in BPF and dynamically loading them. https://github.com/sched-ext/scx/tree/main"
license = "GPL-2.0-only"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
crossbeam = { workspace = true }
ctrlc = { workspace = true }
gpoint = { workspace = true }
itertools = { workspace = true }
libbpf-rs = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
plain = { workspace = true }
scx_stats = { workspace = true }
scx_stats_derive = { workspace = true }
scx_utils = { workspace = true }
serde = { workspace = true }
simplelog = { workspace = true }
zbus = { workspace = true }

[build-dependencies]
scx_utils = { workspace = true }

[features]
enable_backtrace = []
