[package]
name = "scx_flash"
version = "1.0.4"
authors = ["Andrea Righi <arighi@nvidia.com>"]
edition = "2021"
description = "A scheduler designed for multimedia and real-time audio processing workloads. https://github.com/sched-ext/scx/tree/main"
license = "GPL-2.0-only"

[dependencies]
anyhow = { workspace = true }
ctrlc = { workspace = true }
clap = { workspace = true }
crossbeam = { workspace = true }
libbpf-rs = { workspace = true }
log = { workspace = true }
scx_stats = { workspace = true }
scx_stats_derive = { workspace = true }
scx_utils = { workspace = true }
serde = { workspace = true }
simplelog = { workspace = true }

[build-dependencies]
scx_utils = { workspace = true }

[features]
enable_backtrace = []
