[package]
name = "scx_rlfifo"
version = "1.0.6"
authors = ["Andrea Righi <andrea.righi@linux.dev>"]
edition = "2021"
description = "A simple FIFO scheduler in Rust that runs in user-space"
license = "GPL-2.0-only"

[dependencies]
anyhow = { workspace = true }
plain = { workspace = true }
ctrlc = { workspace = true }
libbpf-rs = { workspace = true }
libc = { workspace = true }
scx_utils = { workspace = true }
scx_rustland_core = { workspace = true }

[build-dependencies]
scx_utils = { workspace = true }
scx_rustland_core = { workspace = true }

[features]
enable_backtrace = []
