[package]
name = "scx_mitosis"
version = "0.0.4"
authors = ["Dan Schatzberg <dschatzberg@meta.com>", "Meta"]
edition = "2021"
description = "A dynamic affinity scheduler used within sched_ext, which is a Linux kernel feature which enables implementing kernel thread schedulers in BPF and dynamically loading them. https://github.com/sched-ext/scx/tree/main"
license = "GPL-2.0-only"

[dependencies]
anyhow = { workspace = true }
bitvec = { workspace = true }
cgroupfs = { workspace = true }
clap = { workspace = true }
ctrlc = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
libbpf-rs = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
maplit = { workspace = true }
scx_utils = { workspace = true }
simplelog = { workspace = true }

[build-dependencies]
scx_utils = { workspace = true }

[features]
enable_backtrace = []
