[package]
name = "scx_rustland_core"
version = "2.2.3"
edition = "2021"
authors = ["Andrea Righi <andrea.righi@linux.dev>"]
license = "GPL-2.0-only"
repository = "https://github.com/sched-ext/scx"
description = "Framework to implement sched_ext schedulers running in user space"

[dependencies]
anyhow = { workspace = true }
libc = { workspace = true }
scx_utils = { workspace = true }

[build-dependencies]
scx_utils = { workspace = true }

[lib]
name = "scx_rustland_core"
path = "src/lib.rs"
